import dex.plugins.outlet.v2.util.ReleaseType
import org.codehaus.groovy.runtime.GStringImpl

import java.nio.file.Files

plugins {
	id 'maven-publish'
	id 'io.papermc.paperweight.userdev' version "2.0.0-beta.21"
	id 'xyz.jpenilla.run-paper' version "3.0.2"
	id 'xyz.jpenilla.resource-factory-paper-convention' version "1.3.1"
	id "com.modrinth.minotaur" version "2.+"
	id 'io.github.dexman545.outlet' version "1.7.0-alpha.5"
}

ext {
	var versionPrefixTemp = project.mod_version
	if (!Boolean.parseBoolean(System.getenv("IS_RELEASE"))) {
		String preReleaseVersion = System.currentTimeMillis()

		if (Boolean.parseBoolean(System.getenv("PRESERVE_PRERELEASE_VERSION"))) {
			var preReleaseVersionFile = file("preReleaseVersion.txt").toPath()
			if (Files.exists(preReleaseVersionFile)) preReleaseVersion = Files.readString(preReleaseVersionFile)
			Files.writeString(preReleaseVersionFile, preReleaseVersion)
		}

		var separator = "-"
		if (versionPrefixTemp.contains("-")) separator = "."
		versionPrefixTemp = "${versionPrefixTemp}${separator}${preReleaseVersion}"
	}
	final String versionSuffix = System.getenv("VERSION_SUFFIX")
	versionPrefixTemp = "${versionPrefixTemp}${versionSuffix == null ? "+local" : versionSuffix.isBlank() ? "" : "+${versionSuffix}"}"
	versionPrefixTemp = "${versionPrefixTemp}+paper+${project.minecraft_version}"

	versionPrefix = versionPrefixTemp as GStringImpl

	System.out.println("Version: " + versionPrefix)
}

base {
	archivesName = project.mod_id
	version = project.versionPrefix
}

outlet {
	mcVersionRange = project.supported_minecraft_versions
	allowedReleaseTypes = Set.of(ReleaseType.RELEASE)
}

paperPluginYaml {
	name = project.mod_id.replace('-', '_')
	description = project.mod_description
	main = "eu.pb4.placeholders.impl.PlaceholderAPIMain"
	website = project.mod_website
	apiVersion = outlet.mcVersions().first()
	authors.add("Patbox")
	authors.add("OffsetMonkey538")
}

repositories {
	maven { url = "https://maven.nucleoid.xyz" }
	maven { url = "https://jitpack.io" }
	exclusiveContent {
		forRepository {
			maven {
				name = "PaperMC"
				url = "https://repo.papermc.io/repository/maven-public/"
			}
		}
		filter {
			includeGroupAndSubgroups "io.papermc"
		}
	}
}

sourceSets {
	testmod {
		runtimeClasspath += main.runtimeClasspath
		compileClasspath += main.compileClasspath
	}
}

dependencies {
	paperweight.paperDevBundle project.paper_version

	testmodImplementation sourceSets.main.output
}

tasks.register("testmodJar", Jar) {
	setArchiveClassifier("testmod")
	from(sourceSets.testmod.output)
}

tasks.runServer {
	minecraftVersion project.minecraft_version
	pluginJars(tasks.testmodJar)
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(25)
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25

	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${base.archivesName.get()}"}
	}
}

publishing {
	repositories {
		maven {
			name = "OffsetMonkey538"
			url = "https://maven.offsetmonkey538.top/releases"
			credentials {
				username = providers.gradleProperty("OffsetMonkey538Username").getOrElse(System.getenv("MAVEN_USERNAME"))
				password = providers.gradleProperty("OffsetMonkey538Password").getOrElse(System.getenv("MAVEN_PASSWORD"))
			}
			authentication {
				basic(BasicAuthentication)
			}
		}
	}
	publications {
		register("maven", MavenPublication) {
			afterEvaluate {
				artifactId base.archivesName.get()
			}
			groupId "eu.pb4"
			from components.java
		}
	}
}

modrinth {
	debugMode = Boolean.parseBoolean(System.getenv("MODRINTH_DEBUG"))

	// Main properties
	token = System.getenv("MODRINTH_TOKEN")
	projectId = rootProject.mod_id
	gameVersions = outlet.mcVersions()


	// Version stuff
	def customVersionName = System.getenv("VERSION_NAME")
	if (customVersionName != null) versionName = customVersionName

	versionNumber = "${project.version}"

	def isPreRelease = System.getenv("VERSION_IS_PRERELEASE")
	versionType = Boolean.parseBoolean(isPreRelease) ? "beta" : "release"

	if (project.mod_version.contains("beta")) versionType = "beta"
	if (project.mod_version.contains("alpha")) versionType = "alpha"


	// Files
	additionalFiles = [sourcesJar]


	// Project info
	def changelogEnv = System.getenv("VERSION_CHANGELOG")
	if (changelogEnv != null) changelog = changelogEnv

	autoAddDependsOn = false
}
