# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G

# Minecraft
minecraft_version = 26.1.2
paper_version     = 26.1.2.build.+

supported_minecraft_versions = >=26.1

# Mod Properties
project_name    = 26.1+paper
mod_version     = 3.0.0
mod_name        = Placeholder API Paper
mod_id          = placeholder-api-paper
mod_description = Paper port of Patbox's Text Placeholder API
mod_website     = https://modrinth.com/mod/placeholder-api-paper
mod_issues      = https://github.com/OffsetMods538/TextPlaceholderAPI-Paper/issues
mod_sources     = https://github.com/OffsetMods538/TextPlaceholderAPI-Paper
